server:
  port: 8080

spring:
  application:
    name: order

  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/sampledb?useSSL=false
    username: mysql
    password: root

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true